### ISSUE TITLE
Download data feature not working

### ISSUE THREAD

**Issue by leehart** [cggh/panoptes#496]
http://104.199.5.137/
Variants > Download Data

404 Page Not Found

**Comment by leehart** [comment]
Due to API.serverURL being undefined

**Comment by leehart** [comment]
After defining serverURL in API.js

`http://localhost:8000/api?datatype=downloadtable&database=Samples_and_Variants&qry={%22whcClass%22:%22trivial%22,%22isCompound%22:false,%22isTrivial%22:true,%22Tpe%22:%22%22}&tbname=variants&collist=MoFQxgFgTg9gtjAzvApgPwJIDkAOSCWALvjAHZqjCk5YCGc6AYgBIBqtANgK4oCMaLdtxQAmAW048A~oWgp0oAKIAPQlFpT~LLACUAgoykB1A~N0Gpi09v2HgBoA&posfield=position&order=position&sortreverse=0`


```
2016-09-29 15:30:07 [6388] [ERROR] Error handling request
Traceback (most recent call last):
  File "/[...]/panoptes/build/panoptes_virtualenv/local/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 93, in handle
    self.handle_request(listener, req, client, addr)
  File "/[...]/panoptes/build/panoptes_virtualenv/local/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 139, in handle_request
    for item in respiter:
  File "/[...]/panoptes/build/DQXServer/wsgi_api.py", line 80, in application
    start_response('500 Server Error', [])
  File "/[...]/panoptes/build/panoptes_virtualenv/local/lib/python2.7/site-packages/gunicorn/http/wsgi.py", line 241, in start_response
    raise AssertionError("Response headers already set!")
AssertionError: Response headers already set!
```
