### ISSUE TITLE
Genotypes channel errors

### ISSUE THREAD

**Issue by leehart** [cggh/panoptes#633]
Genotypes

Start > Genome browser > Add channels > Genotypes > haploid
Press "Add 1 channel"

`qajax.js:171 GET http://localhost:8080/panoptes/api?datatype=2d_query&dataset=Genotypes&tabl…roperties=genotype&rowSortCols=&rowOffset=0&rowLimit=100&colFailLimit=1001 500 (Server Error)`

`f7ab43d0-9f52-11e6-b30e-0024e83b1969:1 Uncaught (in promise)`

```
Loading settings from: [...]/sourcedir/datasets/Genotypes/2D_datatables/haploid/settings
SELECT "SnpName","pos","haploid_column_index" FROM "variants" WHERE ((("chrom" = %s)) AND (("pos" >= %s)) AND (("pos" < %s))) AND haploid_column_index IS NOT NULL ORDER BY "pos" LIMIT %s ['Pf3D7_01_v3', '0', '262144', 1002]
Traceback (most recent call last):
  File "[...]/panoptes/server/wsgi_api.py", line 55, in application
    for item in responder.handler(start_response, response):
  File "[...]/panoptes/server/responders/2d_query.py", line 206, in handler
    col_index_field)
  File "[...]/panoptes/server/responders/2d_query.py", line 56, in index_table_query
    dtype = desciptionToDType(desc[1])
  File "[...]/panoptes/server/DQXDbTools.py", line 500, in desciptionToDType
    return dtype[col_type]
KeyError: ('SnpName', 'clob', None, 0, None, None, None)
```

**Comment by benjeffery** [comment]
Thought I'd already fixed this?! I'll double check

**Comment by benjeffery** [comment]
https://github.com/cggh/panoptes/commit/4465e8c868555c68fc95312c272931d3a4055aa3 fixed this - can you confirm?
