### ISSUE TITLE
Errors in Genotypes > Genome Browser

### ISSUE THREAD

**Issue by leehart** [cggh/panoptes#767]
Genotypes Example > Genome Browser

JS console:
`qajax.js:169 POST http://localhost:8080/panoptes/api?datatype=query 500 (Server Error)`
```
:8080/Genotypes/27e72986-d407-11e6-84fc-f8b156aa37dd:1 Uncaught (in promise) XMLHttpRequest {readyState: 4, timeout: 0, withCredentials: false, upload: XMLHttpRequestUpload, responseURL: "http://localhost:8080/panoptes/api?datatype=query"…}
```

Server log:
```
@@@###QRY:SELECT "pos"/1024 AS "window",count(*) AS "count","base" FROM "_sequence_" WHERE ((("chrom" = %s)) AND (("pos" >= %s)) AND (("pos" < %s))) GROUP BY "base","window" ORDER BY "window" asc,"count" desc
@@@###PARAMS:[u'Pf3D7_01_v3', '0', '262144']
Traceback (most recent call last):
  File "[...]/panoptes/server/wsgi_api.py", line 55, in application
    for item in responder.handler(start_response, response):
  File "[...]/panoptes/server/responders/query.py", line 102, in handler
    dtype = desciptionToDType(desc[1])
  File "[...]/panoptes/server/DQXDbTools.py", line 500, in desciptionToDType
    return dtype[col_type]
KeyError: 'bigint'
```

**Comment by leehart** [comment]
Worked around, but #768
